import Head from "next/head";
import { Inter } from "next/font/google";
// import Hero from "@/components/Hero";
// import Sponsors from "@/components/Sponsors";
// import Offers from "@/components/Offers";
// import FeaturedProperty from "@/components/FeaturedProperty";
// import Testimonial from "@/components/Testimonial";
// import PopularProject from "@/components/PopularProject";
// import Subscribe from "@/components/Subscribe";
import Dashboard from "./dashboard";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Home Buddy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{}}>
        <Dashboard />
      </main>
    </>
  );
}
